name: CI
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 20 # Для лучшей поддержки ESM
                  cache: npm
            - run: npm ci
            - run: npm run build
            - run: npm test -- --watchAll=false --ci
              env:
                  NODE_OPTIONS: "--experimental-vm-modules --no-warnings"
                  BABEL_ENV: test

